events: add support for async event handlers
See documentation for details.

One limitation (for now) is that Emiter.add_handler does not support
registering async handlers (`func.ha_async = True` can raise for example
`AttributeError: 'method' object has no attribute 'ha_async'`).